#! /bin/sh
sxhkd &
compton &
xsetroot -cursor_name left_ptr & # sets pointer
# Remove mouse monitor
xrandr --output eDP-1-1 --auto --primary && xrandr --output HDMI-1-1 --off && xrandr --dpi 100


############################
#  WORKSPACES AND BORDERS  #
############################
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           3
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          3
bspc config bottom_padding       3
bspc config left_padding         3
bspc config right_padding        3

bspc rule -a Zathura state=tiled

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#############
#  SCRIPTS #
#############
xrdb /home/jcc/.Xresources
feh --bg-fill ~/Pictures/backgrounds/blue-marble.jpg
bash /home/jcc/.config/polybar/launch.sh
