#! /bin/sh
 
#### AUTOSTART ####
sxhkd &
compton &
xset -b & #For annoying beeping sounds
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
volumeicon &
nm-applet &
polybar top -c $HOME/.config/polybar/config-top.ini &

pulseaudio &
 
 
#### WORKSPACES AND BORDERS ####
 
#Monitor allocation and their workspaces
bspc monitor -d 0 1 2 3 5 8
 
#Border gaps,width, and padding
bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
 
#bspc rule -a gnome-terminal desktop='^1' follow=on
#bspc rule -a Firefox desktop='^2' follow=on
 
#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# wallpaper
feh --bg-fill ~/Pictures/bus-fire.jpg
